### ISSUE TITLE
Great idea!  Looking forward the code!

### ISSUE THREAD

**Issue by zhangxujinsh** [ali-vilab/UniAnimate#1]

**Comment by wangxiang1230** [comment]
Thanks for your attention to UniAnimate. We are sorting out the code and will submit it to the company for approval as soon as possible.

**Comment by YacratesWyh** [comment]
I wonder if there would be any code suggestion for self implementation. If you fail to update like animate anyone, please update your readme to inform community.

**Comment by wangxiang1230** [comment]
> I wonder if there would be any code suggestion for self implementation. If you fail to update like animate anyone, please update your readme to inform community.

Hi, thanks for your reminding, we are sorting out the code and will make the code open source as soon as possible. For more details, please refer to our released paper.

**Comment by Priestru** [comment]
What is code? It's GitHub, we release papers with unverifiable results here for a living.

**Comment by BugsMaker0513** [comment]
最怕阿里式开源

**Comment by wangxiang1230** [comment]
Hi, thanks for your attention. We have submitted the code to company for approval, and the code is expected to be released today or tomorrow.

**Comment by wangxiang1230** [comment]
> 最怕阿里式开源

Hi, thanks for your attention. We have submitted the code to company for approval, and the code is expected to be released today or tomorrow.
