### ISSUE TITLE
why do the pose alignment not use gpt

### ISSUE THREAD

**Issue by SuperEdison** [ali-vilab/UniAnimate#14]
```shell
python run_align_pose.py  --ref_name data/images/WOMEN-Blouses_Shirts-id_00004955-01_4_full.jpg --source_video_paths data/videos/source_video.mp4 --saved_pose_dir data/saved_pose/WOMEN-Blouses_Shirts-id_00004955-01_4_full 
```

but the nvidia-smi show that the program dont use the gpt

![image](https://github.com/ali-vilab/UniAnimate/assets/84554944/5d61a8f9-9898-45e9-8b36-360a03d168c8)

**Comment by wangxiang1230** [comment]
Hi, this situation will not affect the normal operation of the program, thanks.
