### ISSUE TITLE
关于 Pose alignment

### ISSUE THREAD

**Issue by ldqrecord** [ali-vilab/UniAnimate#29]
只能使用cpu运行吗

**Comment by ldqrecord** [comment]
![image](https://github.com/ali-vilab/UniAnimate/assets/75522836/fd73a90b-afde-41a0-8f49-614571aec490)

**Comment by wangxiang1230** [comment]
Pose alignment can be run on a gpu in our cases. We will check this and give the solution as soon as possible.

**Comment by ldqrecord** [comment]
> Pose alignment can be run on a gpu in our cases. We will check this and give the solution as soon as possible.

感谢，我是在windows使用的，按照问题11部署的，不知道是不是和部署环境有关系

**Comment by wangxiang1230** [comment]
> > Pose alignment can be run on a gpu in our cases. We will check this and give the solution as soon as possible.
> 
> 感谢，我是在windows使用的，按照问题11部署的，不知道是不是和部署环境有关系

Hi, thanks for your comments. You can run the pose alignment on gpu by installing onnxruntime-gpu==1.13.1, i.e., pip install onnxruntime-gpu==1.13.1, and we have added the dependency in the requirements.txt. Thanks for your contribution.

**Comment by DecodeW** [comment]
追加一个最新的问题，更新了依赖后，有了新的报错，是代码部分应该也有更新吗？
![error](https://github.com/ali-vilab/UniAnimate/assets/57307920/0d70c152-b5e5-4fd5-94a6-bc8826b1a369)

**Comment by wangxiang1230** [comment]
> 追加一个最新的问题，更新了依赖后，有了新的报错，是代码部分应该也有更新吗？

Hi, it seems that your pose is not detected correctly. You can refer to https://github.com/ali-vilab/UniAnimate/issues/20. The code of pose alignment is not updated, you can try it with the data/videos/source_video.mp4 provided by us. Possible causes of your above problems:
1: pose cannot be detected
2. Some key points of reference images are not present in driving pose at all.
Thanks for your attention.

**Comment by ldqrecord** [comment]
> > > 在我们的案例中，姿势对齐可以在 GPU 上运行。我们将检查这一点并尽快提供解决方案。
> > 
> > 
> > 谢谢，我在windows上使用，按照问题11部署的，不知道它是什么以及部署环境有什么关系
> 
> 嗨，感谢您的评论。您可以通过安装 onnxruntime-gpu==1.13.1（即 pip install onnxruntime-gpu==1.13.1）在 gpu 上运行姿势对齐，并且我们已在 requirements.txt 中添加了依赖项。感谢您的贡献。



> > > 在我们的案例中，姿势对齐可以在 GPU 上运行。我们将检查这一点并尽快提供解决方案。
> > 
> > 
> > 谢谢，我在windows上使用，按照问题11部署的，不知道它是什么以及部署环境有什么关系
> 
> 嗨，感谢您的评论。您可以通过安装 onnxruntime-gpu==1.13.1（即 pip install onnxruntime-gpu==1.13.1）在 gpu 上运行姿势对齐，并且我们已在 requirements.txt 中添加了依赖项。感谢您的贡献。



> > > Pose alignment can be run on a gpu in our cases. We will check this and give the solution as soon as possible.
> > 
> > 
> > 感谢，我是在windows使用的，按照问题11部署的，不知道是不是和部署环境有关系
> 
> Hi, thanks for your comments. You can run the pose alignment on gpu by installing onnxruntime-gpu==1.13.1, i.e., pip install onnxruntime-gpu==1.13.1, and we have added the dependency in the requirements.txt. Thanks for your contribution.

感谢，尝试了问题已解决
