### ISSUE TITLE
Ask about pre-trained video generation model

### ISSUE THREAD

**Issue by Sainzerjj** [ali-vilab/UniAnimate#52]
Excellent job! I want to ask about the specific version of the pre-trained video generation model TFT2V used to train UniAnimate, because I see many related models on modelscope.
![image](https://github.com/ali-vilab/UniAnimate/assets/96109403/23e80f1d-93ac-433c-9ba8-83465fdfe47d)

**Comment by wangxiang1230** [comment]
Hi, thanks for your attention. The pretrained weight we used is ```tft2v_vcomposer_non_ema_254000.pth```.
