### ISSUE TITLE
The training detail for UniAnimate

### ISSUE THREAD

**Issue by Sainzerjj** [ali-vilab/UniAnimate#57]
Great work! I have a few questions regarding the training process for Unianimate:

1. Should the training be conducted in phases, similar to Animate Anyone (two stages)?
2. If the training is done just in a single phase, are all parameters in both UNet and the pose guider updated simultaneously? Would this cause instability during training or lead to a decline in quality?
3. In the inference code (inference_unianimate_entrance.py), I noticed that classifier-free guidance is used and you set all conditions to None as "uncond" in classifier-free guidance. During training, do you randomly set all or some of the conditions to None with a certain probability to support this guidance? I am asking because I observed that in Animate Anyone, only the features encoded from ref_image are set to zero. Therefore, I am particularly interested in this operaion.
Deeply looking forward to your response！Thanks！

**Comment by wangxiang1230** [comment]
Refer to issue https://github.com/ali-vilab/UniAnimate/issues/55 for more details.
