### ISSUE TITLE
Videos (and output images) are not saved after inferring

### ISSUE THREAD

**Issue by xuanlongORZ** [ali-vilab/UniAnimate#6]
maybe it is better to erase 'os.system(f'rm -rf {frame_dir}')' in this line, otherwise nothing will be saved but just a log file: 
https://github.com/ali-vilab/UniAnimate/blob/4e5bed683136cdd5489d6202f34b2fe87a5902eb/utils/video_op.py#L325

BTW, maybe it is better to save a video using cv2.VideoWriter in the for-loop above the above line.

**Comment by wangxiang1230** [comment]
> maybe it is better to erase 'os.system(f'rm -rf {frame_dir}')' in this line, otherwise nothing will be saved but just a log file:
> 
> https://github.com/ali-vilab/UniAnimate/blob/4e5bed683136cdd5489d6202f34b2fe87a5902eb/utils/video_op.py#L325
> 
> BTW, maybe it is better to save a video using cv2.VideoWriter in the for-loop above the above line.

Hi, thanks for your suggestion. We did this in order to save only the .mp4 file and not the images.

**Comment by xuanlongORZ** [comment]
OK I see.. but by running directly the inference code, I didn't get either images or the video LOL, that's why I raised this issue. I'm not sure if it happens only on me..

**Comment by JunrQ** [comment]
My `ffmpeg` failed to save the video due to no 'x264' encoder.

> OK I see.. but by running directly the inference code, I didn't get either images or the video LOL, that's why I raised this issue. I'm not sure if it happens only on me..

**Comment by Starzilla29** [comment]
It appeared in UniAnimate/outputs/custom_infer_long/ for me, is it not there for you?

**Comment by wangxiang1230** [comment]
Hi, the bug is fixed. Please refer to https://github.com/ali-vilab/UniAnimate/blob/7417161cfface7c36ca1682b2b57127e8f2ff3e7/utils/video_op.py#L325-L332

Thank @xuanlongORZ for the suggestion.

**Comment by xuanlongORZ** [comment]
> Hi, the bug is fixed. Please refer to
> 
> https://github.com/ali-vilab/UniAnimate/blob/ea6d185e894939b66502e6a60dfbe7451430ba35/utils/video_op.py#L317-L340
> 
> Thank @xuanlongORZ for the suggestion.

It works ! Thank you for your awesome work :D
