### ISSUE TITLE
伪影问题

### ISSUE THREAD

**Issue by wangxr1999** [ali-vilab/UniAnimate#63]
你好！很棒的工作，在部分推理结果中发现伪影问题，看起来和ref部分区域类似，请问大概是什么原因？
<img width="165" alt="pic" src="https://github.com/user-attachments/assets/417a2872-ea10-4b02-bfd1-c6bae3ef27e4">
<img width="164" alt="pic2" src="https://github.com/user-attachments/assets/316a9cff-d8d6-42b9-b2fe-5ebb90e5f4c2">

**Comment by wangxiang1230** [comment]
嗨，感谢你的关注。这种伪影来自于原来视频的问题可能原因是noise prior加重了。如果是长视频生成的结果，你可以调整https://github.com/ali-vilab/UniAnimate/blob/d7814fa44a0a1154524b92fce0e3133a2604d333/configs/UniAnimate_infer_long.yaml#L101

noise_prior_value: 939 --> 949/959/969等大一点的参数。

如果是短视频生成，可以调整https://github.com/ali-vilab/UniAnimate/blob/d7814fa44a0a1154524b92fce0e3133a2604d333/configs/UniAnimate_infer.yaml#L98

noise_prior_value: 949 到 959/969. 

谢谢关注。
