### ISSUE TITLE
怎么生成长视频？

### ISSUE THREAD

**Issue by XuJianzhi** [ali-vilab/UniAnimate#64]
非常感谢作者的工作。

请问修改哪里能生成长视频，而不仅截取前三秒呢？

**Comment by wangxiang1230** [comment]
Hi, 我们有长视频生成的脚本的，你可以参考https://github.com/ali-vilab/UniAnimate/blob/main/README.md#43-generating-long-videos

或者直接运行以下命令：python inference.py --cfg configs/UniAnimate_infer_long.yaml 

谢谢关注。
