### ISSUE TITLE
Issue with Installing Requirements: ReadTimeoutError with aiofiles

### ISSUE THREAD

**Issue by ironico** [ali-vilab/UniAnimate#7]
I am encountering an issue when trying to install the project's dependencies using the command:

```shell
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
```

The installation process repeatedly retries and eventually fails with the following error messages:

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
ERROR: Could not find a version that satisfies the requirement aiofiles==23.2.1 (from versions: none)
ERROR: No matching distribution found for aiofiles==23.2.1
```

It seems like the connection to the PyPI mirror at `https://pypi.tuna.tsinghua.edu.cn` is timing out, specifically when trying to find the package `aiofiles==23.2.1`.

Has anyone encountered a similar issue or have any suggestions on how to resolve this? Any help would be greatly appreciated!

**Comment by wangxiang1230** [comment]
> aiofiles

Hi, you can remove the aiofiles python package from the requirements.txt.

**Comment by xuanlongORZ** [comment]
well, I think it is for Chinese developers .. try not use tsinghua mirror by just erasing it (not sure if it works, but if you are stacked at connection issue, it might be the case). 
BTW, the requirements seem to be directly copied from the environment, and you might come across some other problems when it runs to, for example, torch==2.0.1+cu118 .

**Comment by wangxiang1230** [comment]
> well, I think it is for Chinese developers .. try not use tsinghua mirror by just erasing it (not sure if it works, but if you are stacked at connection issue, it might be the case). BTW, the requirements seem to be directly copied from the environment, and you might come across some other problems when it runs to, for example, torch==2.0.1+cu118 .

Hi, thanks for pointing out this. We will fix it as soon as possible.

**Comment by ironico** [comment]
I have removed the link to the PyPI mirror and tried to install the requirements. However, I noticed that some libraries, such as motion-vector-extractor, are only available for Linux, while I was trying on a Windows machine.

To resolve this, I will attempt to use WSL  or Docker to create a compatible environment.

For this reason, I will close the issue. Thank you for your support.

**Comment by wangxiang1230** [comment]
> motion-vector-extractor



> I have removed the link to the PyPI mirror and tried to install the requirements. However, I noticed that some libraries, such as motion-vector-extractor, are only available for Linux, while I was trying on a Windows machine.
> 
> To resolve this, I will attempt to use WSL or Docker to create a compatible environment.
> 
> For this reason, I will close the issue. Thank you for your support.

Hi, some python packages such as motion-vector-extractor can be deleted from the requirements as it is not used.
